### ISSUE TITLE
ACCESS_NETWORK_STATE Permission

### ISSUE THREAD

**Issue by aritraroy** [path/android-priority-jobqueue#103]
It seems that I need this permission anyway to use Jobs. Is there anyway I can omit this permission and still use it?

**Comment by yigit** [comment]
Yes. Provide a custom NetworkUtil in the configuration builder.

**Comment by aritraroy** [comment]
Can you please provide an example how to do that? None, of my Jobs are using Internet in any way. It would be really helpful if I can get a way to omit this permission.

**Comment by yigit** [comment]
Here are the docs on how to configure job manager.

https://github.com/yigit/android-priority-jobqueue/wiki/Job-Manager-Configuration

Just provide a network util that returns false. Please take a look at other configuration options too, you are relying a big chunk of your app on this library so it is best to know it works before using.

There is valuable information here as well:
https://github.com/path/android-priority-jobqueue/wiki/Job-Configuration

Also see: #99 .

**Comment by aritraroy** [comment]
It is working perfectly now. Thanks a lot for it.

As recommended, I have also implemented the the NetworkEventProvider, do I need to do anything specific in the setListener method?

**Comment by yigit** [comment]
No, since you'll never dispatch network changed event. This setup should be good.

**Comment by aritraroy** [comment]
Thanks a lot for all the help. :-)
