### ISSUE TITLE
Provide a way to delete underlying database files

### ISSUE THREAD

**Issue by daj** [path/android-priority-jobqueue#56]
I create a separate instance of the JobManager for each of my automated tests.  In the setUp() for each test I set the ID to be a unique String based on System.currentTimeMillis():

    mJobManagerName = MyTestUtil.getUniqueID();
    Configuration configuration = new Configuration.Builder(context)
                .id(mJobManagerName)
                <snip>
                .build();
    mJobManager = new JobManager(context, configuration);

Then in my tearDown() I stop and clear the job manager:

    mJobManager.stop();    
    mJobManager.clear();

Unfortunately I can see that lots of database files are leftover after running my test suite, e.g.

    -rw-rw---- u0_a49   u0_a49      20480 2014-07-24 22:04 db_1406228676565
    -rw------- u0_a49   u0_a49      24072 2014-07-24 22:04 db_1406228676565-journal

This isn't causing an issue right now as the files are small, but we need a reliable way to remove them.  Perhaps .clear() should tidy them up?

In the short term I will probably workaround this by deleting the files in my test tearDown(), e.g.

    File dbFile = getContext().getDatabasePath("db_" + mJobManagerName);
    File journalFile = getContext().getDatabasePath("db_" + mJobManagerName + "-journal");

**Comment by yigit** [comment]
This issue was moved to yigit/android-priority-jobqueue#10
