### ISSUE TITLE
Do jobs run when application is closed?

### ISSUE THREAD

**Issue by gdogaru** [path/android-priority-jobqueue#65]
Hi,
Let's say I have some jobs that require internet.
Do they get triggered if the application is closed? I see that the network state receiver is declared for code and I am not sure if it receives a call if the app is not running.
If not, do you have an example on how to do it in this case? 
also, if the phone is rebooted, etc, is the library restarting the job processing when the phone starts back?
Thanks
(sorry for posting here, I couldn't find a forum)

**Comment by yigit** [comment]
JobManager does not wake up if network is changed but you can wake your application up to do this. We don't want to enforce this since we don't know the requirement.
