### ISSUE TITLE
Are nested Jobs OK?

### ISSUE THREAD

**Issue by an-k** [path/android-priority-jobqueue#72]
Hello, 

is nesting jobs dangerous - maybe just under certain circumstances?

I want to load data from a remote server on the first start and when online (Network required) or saved data from the disk otherwise. 
I'm doing it like so right now:
In my Activity I'm calling  `jobManager.addJobInBackground(new GetDataJob());` (No NetworkRequired)
This job checks the disk data, its age, the network condition and either calls
`jobManager.addJob(new LoadDataRemoteJob());` (NetworkRequired)
or
`jobManager.addJob(new LoadDataLocalJob());` (no NetworkRequired)
itself in its `onRun()`.

The `LoadData...`-Jobs do the real work. 
It's working but I don't know if this composition could cause problems?
Also should I call the real jobs by `addJobInBackground` instead of the helper job?

Thank you for this great library - really saved me a lot of time

**Comment by yigit** [comment]
It is fine to add jobs inside jobs. There are similar cases in Path application as well.
