### ISSUE TITLE
How do I use a content provider from a Job?

### ISSUE THREAD

**Issue by deanezra** [path/android-priority-jobqueue#73]
I have created a job that downloads data from a web api and then I want to write the data to my content provider.

But I cant get hold of the ContentResolver (because I don't have a context):

ContentProviderClient 
provider=getContentResolver().acquireContentProviderClient(NewsContentProvider.AUTHORITY);

I see that the JobManager has a instance of Context, but I cant see how I get to context from the job.

Is there a suggested way to use content provider inside a job?

**Comment by yigit** [comment]
Use application context. Jobs should not need any other context (if they do, it is wrong).
