### ISSUE TITLE
Example of Dagger DI injection into JobManager

### ISSUE THREAD

**Issue by Yougin** [path/android-priority-jobqueue#75]
It isn't evident how to make Dagger to inject things into Jobs using injector(DependencyInjector injector) method, could you please refer to an example? Thank you very much.

update: I've found an example in your tests, it looks like I can use it only with BaseJob which is deprecated, is that true?

**Comment by alpha-centauri** [comment]
I had trouble understanding the injection part as well. Thanks to Yigit's example project I got the idea: https://github.com/yigit/android-livecode-demo/tree/master/app/src/main/java/com/birbit/android/livecode/twitter
So for anyone else interested, just refer to MyJobManager.java and App.java.
