### ISSUE TITLE
Does the JobManager keep the cpu awake?

### ISSUE THREAD

**Issue by shun250** [path/android-priority-jobqueue#79]
Does the JobManager keep the cpu awake to ensure the job will run when the system decides to close the application. Or would I need to put wakelocks on the application to ensure the job get run?

**Comment by yigit** [comment]
No, we don't keep any wake locks since it is easy to make mistakes there. You can manage wake locks manually for your important tasks but be very careful as you can easily drain battery by a leaked wake lock.

**Comment by farmazon3000** [comment]
It would be nice to state this in ```README.md``` that you don't do that.
