### ISSUE TITLE
"Network" does not require "Internet"

### ISSUE THREAD

**Issue by anti43** [path/android-priority-jobqueue#80]
Job is created with requireNetwork() - device connects to wifi with no internet access -> job runs (but fails, as no server at all but the wifi router is reachable. 

Maybe a "requireInternet" with check to 8.8.8.8 or something maybe required? Or custom 

requireTrue(new Callable<Boolean>(){
   public Boolean call(){
        //do ping some server
   }
})

**Comment by alfishe** [comment]
Just provide NetworkUtil interface derived class instance with implementation you prefer.

Example:
Configuration configuration = new Configuration.Builder(context).networkUtil(<your_implementation_class_instance>)... .build();
JobManager jobManager = new JobManager(context, configuration);

**Comment by anti43** [comment]
so cool! thanks!!

**Comment by mecid** [comment]
@anti43 
This is my implementation with google dns ping
https://gist.github.com/mecid/1e5dc9a41ed413c99121
