### ISSUE TITLE
Custom NetworkUtil make isConnected async

### ISSUE THREAD

**Issue by faken** [path/android-priority-jobqueue#82]
We have implemented a custom NetworkUtil which checks if the device can access the network (via CONNECTIVITY_SERVICE) and also checks if our backend service is available (sends a ping and expects a pong). 

We have realized that our application will be frequently used in environments with a captive portal - so that the first condition applies and the later one fails. 

Our problem is, that the call to isConnected is made synchronously and a boolean return value is expected. This way we are forced to make our backend ping request synchronously as well, which causes the main thread to halt. 

We know that this is a special requirement and maybe it should be solved by android-priority-jobqueue, but maybe you have a solution to our problem. Making the Ping-Request is as far as i know impossible because of the expected boolean return-value of the isConnected-Method.

**Comment by mecid** [comment]
@faken any solution for this problem?

**Comment by mecid** [comment]
@faken async implementation https://gist.github.com/mecid/1e5dc9a41ed413c99121
