### ISSUE TITLE
Running as a thread and not as a service

### ISSUE THREAD

**Issue by efi-mk** [path/android-priority-jobqueue#83]
Hi,

A general question, the fact that the jobs are running in a thread and not part of a component (Service for example) might cause Android to kill the process even though the jobs are not done yet ?

I know for example that running something as a service will keep the Android process in the Air, one of the benefits of a service is the ability to define it as sticky so even if Android kills us it will start us as soon as resources are available.

**Comment by yigit** [comment]
You can create the job queue inside a service, we just didn't want to enforce it.
