### ISSUE TITLE
Job Delay is not working for 30 seconds

### ISSUE THREAD

**Issue by shun250** [path/android-priority-jobqueue#84]
I have a Job and when i set the delay for 10000 ms(10 seconds) the code works. The job will run with a delay. But when I increase it to 30 seconds the job almost never runs. When I am lucky the job will run. I seem to be able consistently get the delayed job to run by adding another job to the queue.

**Comment by aashrairavooru** [comment]
I am getting the same problem delayed jobs work when the want to can we get some clarity on their woking

**Comment by yigit** [comment]
This issue was moved to yigit/android-priority-jobqueue#8
