### ISSUE TITLE
ReRun Jobs every 5 sec-Alarm

### ISSUE THREAD

**Issue by chkm8** [path/android-priority-jobqueue#87]
Hi, I would like to ask assistance if android-priority-jobqueue has a functionality of scheduling jobs to run in a certain time or should I still use a Alarm Manager or ScheduledThreadPoolExecutor to schedule my jobs. I've been looking on the documents/wiki and searching in the web but i could not find example for this situation.

I already tried creating my job and Jobmanager.

/**RUN CURRENT LOCATION UPDATE*/
    private void updateCurrentLocation(){

        Configuration configuration = new Configuration.Builder(this)
                .customLogger(new CustomLogger() {
                    private static final String TAG = "JOBS";
                    @Override
                    public boolean isDebugEnabled() {
                        return true;
                    }
                    @Override
                    public void d(String text, Object... args) {
                        Log.d(TAG, String.format(text, args));
                    }
                    @Override
                    public void e(Throwable t, String text, Object... args) {
                        Log.e(TAG, String.format(text, args), t);
                    }
                    @Override
                    public void e(String text, Object... args) {
                        Log.e(TAG, String.format(text, args));
                    }
                })
                .minConsumerCount(1)//always keep at least one consumer alive
                .maxConsumerCount(3)//up to 3 consumers at a time
                .loadFactor(3)//3 jobs per consumer
                .consumerKeepAlive(5)//wait 5 sec
                .build();
        JobManager jobManager = new JobManager(this,configuration);
        jobManager.addJobInBackground(new UpdateVehicleCurrentLocation(12.45,1212.67));
    }

I want to have a scheduled job that would send updates to my api about the current location of the user. 

If this question already asked, I apologize and would love to know the answer.

Thank you so much

**Comment by yigit** [comment]
Sorry, this is not something supported. It is best if you just create a component that does the scheduling.
