### ISSUE TITLE
Bad explanation for onAdded() when using addJobInBackground

### ISSUE THREAD

**Issue by m4hmoud** [path/android-priority-jobqueue#88]
I was just trying this in my app and I read the documentation for the `onAdded()` method:

> This is a good place to dispatch a UI event...

My first thought was this is like pre-process in AsyncTask and it runs in the same thread (in this case UI thread) that it was called. But it seems that when using `addJobInBackground(job)`, this method is also called in the background thread. Thus, not really a good place for UI change logic...

Am I missing something or shouldn't this logic be mentioned in the docs?

**Comment by mecid** [comment]
@m4hmoud just use event bus to send event to your UI

**Comment by m4hmoud** [comment]
@mecid I have no problem implementing the UI change. I just thought the documentation was misleading. I think it should mention that all the methods are running the background thread when `addJobInBackground()` is used.

**Comment by mecid** [comment]
@m4hmoud may be) but i am using eventbus only on UI thread.

**Comment by yigit** [comment]
This issue was moved to yigit/android-priority-jobqueue#6
