### ISSUE TITLE
How to retry the job according to the server response?

### ISSUE THREAD

**Issue by athulcek** [path/android-priority-jobqueue#91]
i coded like this  

if (execute())
throw new ErrorUtils("an exception");

execute will return a boolean value if the server response is false,so i need to re-try 
here im getting an error 
"BoxInsert" is my job class

01-30 14:51:05.630: E/(29248): error while executing job
01-30 14:51:05.630: E/BoxInsert(29248): java.lang.Exception: an exception
01-30 14:51:05.630: D/(29248): re-adding job 45
01-30 14:51:05.670: E/(29248): error while serializing object BoxInsert

**Comment by yigit** [comment]
can you share your job? Looks like it is persistent but not serializable.

**Comment by athulcek** [comment]
import java.util.ArrayList;

import org.apache.http.NameValuePair;
import org.apache.http.message.BasicNameValuePair;
import com.path.android.jobqueue.Job;
import com.path.android.jobqueue.Params;
import com.thoughtworks.xstream.XStream;
import com.wbpro.solaft.Log.MLog;
import com.wbpro.solaft.Utils.AppConstant;
import com.wbpro.solaft.Utils.BeanService;
import com.wbpro.solaft.database.FilterInfo;
import com.wbpro.solaft.events.ErrorUtils;
import com.wbpro.solaft.network.HttpException;
import com.wbpro.solaft.network.HttpResponse;
import com.wbpro.solaft.network.SoapClient;
import com.wbpro.solaft.network.SoapClient.RequestService;

public class BoxInsert extends Job {
	private static final String TAG = BoxInsert.class.getSimpleName();
	private HttpResponse<String> Response;

	private ArrayList<FilterInfo> filter_to_insert;
	private static final int PRIORITY = 0;

	public BoxInsert(ArrayList<FilterInfo> filter_to_insert) {
		super(new Params(PRIORITY).requireNetwork().persist());
		this.filter_to_insert = filter_to_insert;
	}

	@Override
	public void onRun() throws Throwable {

		if (execute())
			throw new ErrorUtils("an exception");
	}

	private boolean execute() {
		XStream xstream = new XStream();
		xstream.alias("ID", FilterInfo.class);
		xstream.aliasType("ID", FilterInfo.class);
		xstream.aliasField("IDNumber", FilterInfo.class, "ID");

		ArrayList<NameValuePair> nameValuePairs = new ArrayList<NameValuePair>();

		nameValuePairs.add(new BasicNameValuePair("StrUFID", xstream
				.toXML(filter_to_insert)));
		 
		 
		SoapClient ss = new SoapClient(nameValuePairs, AppConstant.BOX_INSERT);

		try {
			ss.execute(RequestService.SaveBackService);
		} catch (HttpException e) {
			Response = new HttpResponse<String>();
			Response.setHasError(true);
			Response.setErrorTrace(e.toString());
			e.printStackTrace();

		}
		Response = ss.getResponse();
		if (!Response.isHasError()) {
			MLog.sysOut(Response.getContent());
			return false;
		} else {

			return true;

		}

	}

	@Override
	public void onAdded() {

	}

	@Override
	protected void onCancel() {
		// TODO Auto-generated method stub

	}

	@Override
	protected boolean shouldReRunOnThrowable(Throwable arg0) {
		MLog.e(TAG, arg0.toString());
		return true;
	}
}

**Comment by yigit** [comment]
I assume `HttpResponse` and/or `FilterInfo` is not serializable. Why are they fields in the job anyways?

**Comment by athulcek** [comment]
HttpResponse was not serializable 

HttpResponse is for handling the response from the server and FilterInfo is for handling the internal data in may project 

thank you for the reply let me try with this will reply after testing this.

**Comment by LOG-TAG** [comment]
@athulcek  I have created one eclipse sample for understanding retry logic long back ago hope this helps !! https://github.com/LOG-TAG/android-priority-jobqueue-examples/blob/master/TodoListRetryCountSample/src/com/apjq/todolist/jobs/SyncDataJob.java

**Comment by yigit** [comment]
This issue was moved to yigit/android-priority-jobqueue#4
