### ISSUE TITLE
Unwanted duplication of jobs in a queue

### ISSUE THREAD

**Issue by ckozak** [path/android-priority-jobqueue#92]
I have a following scenario in which I consistently get duplication of jobs.

```java
Configuration configuration = new Configuration.Builder(getContext())
                .minConsumerCount(1) //always keep at least one consumer alive
                .maxConsumerCount(1) //up to 3 consumers at a time
                .loadFactor(1) //3 jobs per consumer
                .consumerKeepAlive(120) //wait 2 minute
                .build();
```
I'm trying to get sequential jobs execution. Parallelization is not that important to me.

- Execute a job with a network call (with .requireNetwork().persist()).
- It fails with an AuthException. At this point I call jobManaber.stop() because  any subsequent job execution will fail with the same AuthException and I need to re-login.

```java
@Override
    protected void onCancel() {

    }

    @Override
    protected boolean shouldReRunOnThrowable(Throwable throwable) {
        return throwable instanceof AuthException;
    }
```

- When I relogin I call jobManager.start() to continue jobs execution.
- I consistently get 2-3 duplicated jobs at this point.

**Comment by ckozak** [comment]
it looks like a race condition. I checked that .addJobInBackground is called only once but a new consumer is added just after a job runs and the new consumer picks up the same job and executes it too.

```

02-06 22:35:08.375  15253-15328/com.package.staging D/JOBS﹕ added job id: 46 class: DeleteDictionaryJob priority: 1000 delay: 0 group : d persistent: true requires network: true
02-06 22:35:08.395  15253-16065/com.package.staging D/JOBS﹕ running job DeleteDictionaryJob
02-06 22:35:08.396  15253-15328/com.package.staging D/JOBS﹕ pool-2-thread-1: load factor check. false = (1 < 1)|| (1 * 1 < 0 + 1). consumer thread: false
02-06 22:35:08.438  15253-15253/com.package.staging D/JOBS﹕ main: load factor check. true = (0 < 1)|| (0 * 1 < 1 + 0). consumer thread: false
02-06 22:35:08.438  15253-15253/com.package.staging D/JOBS﹕ adding another consumer
02-06 22:35:08.443  15253-16164/com.package.staging D/JOBS﹕ starting consumer Thread-3229
02-06 22:35:08.511  15253-16164/com.package.staging D/JOBS﹕ running job DeleteDictionaryJob
02-06 22:35:08.520  15253-16065/com.package.staging D/JOBS﹕ finished job DeleteDictionaryJob
02-06 22:35:08.598  15253-16164/com.package.staging D/JOBS﹕ finished job DeleteDictionaryJob
```

**Comment by mecid** [comment]
@ckozak i have no problems like this. I am using default consumer configuration. Just using grouping if don't want to run certain jobs in parallel.

**Comment by ckozak** [comment]
Unfortunately even default configuration with grouping doesn't work for me. Nothing changes at all, some jobs are duplicated on every call, some are not. But every job is executed even more, 3-5 times when I call jobManager.start/stop. All my jobs extend the same base class and are essentially the same, with a difference in a network call they make.

**Comment by mecid** [comment]
@ckozak i thinks this is bad idea using start/stop method.

**Comment by ckozak** [comment]
@mecid Originally I thought that start/stop is a source of problem, but I saw duplication even without it. Start/Stop just made if much more visible.

**Comment by mecid** [comment]
@ckozak very interesting, but i didn't see any duplicate.

**Comment by yigit** [comment]
This issue was moved to yigit/android-priority-jobqueue#3
