### ISSUE TITLE
Error while serializing object StatusUpdateJob

### ISSUE THREAD

**Issue by mecid** [path/android-priority-jobqueue#93]
error while serializing object StatusUpdateJob
    java.io.NotSerializableException: com.aaplab.robird.event.MainThreadBus

public abstract class BaseTwitterJob extends Job {

    public static final int UX = 1000;
    public static final int HIGH = 800;
    public static final int MID = 500;
    public static final int LOW = 0;

    @Retention(RetentionPolicy.SOURCE)
    @IntDef({UX, HIGH, MID, LOW})
    public @interface Priority {
    }

    @Inject
    Context context;

    @Inject
    Bus bus;

    protected Account account;
    protected Twitter twitter;
    protected long id;

    public BaseTwitterJob(Params params, Account account) {
        super(params);
        this.account = account;
        this.twitter = createTwitter(account);
    }

    public void setId(long id) {
        this.id = id;
    }

    @Override
    public void onAdded() {

    }

    @Override
    protected void onCancel() {

    }

    @Override
    protected boolean shouldReRunOnThrowable(Throwable throwable) {
        Timber.e("", throwable);
        return false;
    }

    public static Twitter createTwitter(Account account) {
        ConfigurationBuilder builder = new ConfigurationBuilder();
        builder.setOAuthConsumerKey(SignInActivity.CONSUMER_KEY);
        builder.setOAuthConsumerSecret(SignInActivity.CONSUMER_SECRET);
        return new TwitterFactory(builder.build()).getInstance(new AccessToken(account.token, account.tokenSecret));
    }
}

public class StatusUpdateJob extends BaseTwitterActionJob {

    private String text;
    private long inReplyTo;

    public StatusUpdateJob(Account account, String text) {
        super(account);
        this.text = text;
    }

    public StatusUpdateJob(Account account, String text, long inReplyTo) {
        this(account, text);
        this.inReplyTo = inReplyTo;
    }

    @Override
    public void onRun() throws Throwable {
        StatusUpdate statusUpdate = new StatusUpdate(text);

        if (inReplyTo > 0)
            statusUpdate.inReplyToStatusId(inReplyTo);
        twitter.updateStatus(statusUpdate);
    }
}

**Comment by mecid** [comment]
Fixed by adding transient to injectable fields

**Comment by behl1** [comment]
Hey, a bit off topic but how are you Injecting the fields in your code. Having an issue with that. Will be highly obliged if you could help.
