### ISSUE TITLE
Sticky events producer in the Job

### ISSUE THREAD

**Issue by mecid** [path/android-priority-jobqueue#97]
I have Job which produce sticky event as a result of the Job. But i need to register Job to provide sticky events. Which lifecycle methods of the Job i need to use for register/unregister ? I am using Otto event bus.

**Comment by yigit** [comment]
Are you trying to listen for events from your job? That seems unexpected.
Or do you need to register just to dispatch events?
I never used otto so I don't know but needing to register to dispatch events seems weird too.

Unfortunately, there is no "done" callback in jobs :/. We can consider adding one but can you add more details on why this is needed?

**Comment by yigit** [comment]
This issue was moved to yigit/android-priority-jobqueue#1
