### ISSUE TITLE
Kryofication needed to optimise serialization!! 

### ISSUE THREAD

**Issue by LOG-TAG** [path/android-priority-jobqueue#98]
I'm just thinking of optimizing this awesome lib with use of  kryo serialization which is more efficient compare to Java serialization

https://github.com/EsotericSoftware/kryo Java serialization and cloning: fast, efficient, automatic  !!

**Comment by yigit** [comment]
You can use a custom job serializer, see the [javadoc][1].
http://path.github.io/android-priority-jobqueue/javadoc/com/path/android/jobqueue/config/Configuration.Builder.html#jobSerializer(com.path.android.jobqueue.persistentQueue.sqlite.SqliteJobQueue.JobSerializer)

I don't think it is a good idea to add another dependency.
